config/routes.rb
RedditOnRails::Application.routes.draw do

  devise_for :users
  resources :pages
  resources :links
  resources :comments
  resources :votes
  

  root 'pages#index'

  get 'search' => 'search#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
	belongs_to :link

end

app/models/link.rb
class Link < ActiveRecord::Base

	belongs_to :user
	has_many :comments
	has_many :votes

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base

	validates :user_id, uniqueness: { scope: :link_id }

	belongs_to :user
	belongs_to :link

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_filter :authenticate_user!

  def create
    @comment = current_user.comments.create(comment_params)
    redirect_to :back
  end

  private

	def comment_params
		params.require(:comment).permit(:message, :user_id, :link_id)
	end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def show
		@link = Link.find(params[:id])
		@comment = Comment.new
	end

	def new
		@link = Link.new
	end

	def create
		@link = Link.new(link_params)
		if @link.save
			redirect_to @link
		else
			render 'new'
		end
	end

	private

	def link_params
		params.require(:link).permit(:title, :url)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@links = Link.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
		@links = Link.advanced_search(:title => params[:q]).page(params[:page]).per_page(20)
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  before_filter :authenticate_user!

  def create
    @vote = current_user.votes.where(link_id: params[:vote][:link_id]).first
		@vote ||= current_user.votes.create(vote_params)
		@vote.update_attributes(vote_params)
    redirect_to :back
  end

  private

	def vote_params
		params.require(:vote).permit(:user_id, :link_id, :up)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
	  <title>RedditOnRails</title>
	  <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
 
          <!-- Be sure to leave the brand out there if you want it shown -->
          <%= link_to "RedditOnRails", root_path, class: "brand" %>
     
          <!-- Everything you want hidden at 940px or less, place within here -->
          <div class="nav-collapse collapse">
            <!-- .nav, .navbar-search, .navbar-form, etc -->
            <%# user is logged in, show log out link %>
            <ul class="nav pull-right">
              <% if current_user.present? %>
                <li><p class="navbar-text"><%= current_user.email %></p></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                <%# user is not logged in, show signup and login links %>
              <% else %>
                <li><%= link_to 'Sign In', new_user_session_path %></li>
                <li><%= link_to 'Register Now!', new_user_registration_path %></li>
              <% end %>
            </ul>     
          </div>
        </div>
      </div>
    </div>

    

    <div class="container">
      <div class="row">
  			<div class="span6">
          <% [:notice, :error, :alert].each do |level| %>
  				  <% unless flash[level].blank? %>
    				  <div data-alert="alert" class="alert alert-<%= level %> fade in">
      				  <a class="close" data-dismiss="alert" href="#">&times;</a>
      				  <%= content_tag :p, flash[level] %>
    				  </div>
  				  <% end %>
				  <% end %>
					
          <%= yield %>

        </div>
        <div class="span4">
          <div class="well">
            <h3>Search</h3>
            <%= form_tag(search_path, method: "get", class: "form-search") do %>
              <%= text_field_tag(:q, nil, class: "input-medium search-query") %>
              <%= submit_tag("Search", class: "btn") %>
            <% end %>
          </div>
          <%= link_to "Add a link", new_link_path, class: "btn btn-large btn-primary" %>
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/links/create.html.erb
<h2>Create</h2>

app/views/links/new.html.erb


<div class="well">
  <h2>Add a Link</h2>  
  <%= form_for @link do |f| %>
    <% if @link.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

        <ul>
        <% @link.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :url %><br />
      <%= f.text_field :url %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/links/show.html.erb
<h2><%= @link.title %></h2>
(<%= link_to @link.url, @link.url %>)


<h3>Comments</h3>

<div>
	<ul>
		<% @link.comments.each do |comment| %>
			<li><%= comment.message %></li>
		<% end %>
	</ul>
</div>

<%= form_for @comment do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message, :placeholder => "Add a comment" %>
     <%= f.hidden_field :link_id, :value => @link.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/index.html.erb

<ul>
	<% @links.each do |link| %>
		<li><h3><%= link_to link.title, link.url %> <small>(<%= link_to link.url, link.url %>)</small></h3></li>
		<%= link_to "comments", link %>
		<p>
			<% if current_user && current_user.votes.where(link_id: link.id, up: true).present? %>
    		*
  		<% else %>
    		<%= link_to "+", votes_path(vote: {link_id: link.id, up: true}), method: :post %>
  		<% end %>
  		<% if current_user && current_user.votes.where(link_id: link.id, up: false).present? %>
    		*
  		<% else %>
    		<%= link_to "-", votes_path(vote: {link_id: link.id, up: false}), method: :post %>
  		<% end %>
			Votes: <%= link.votes.where(up: true).count - link.votes.where(up: false).count %>
		</p>
	<% end %>
</ul>

<%= will_paginate @links %>

app/views/search/index.html.erb
Here are all the links that matched "<%= params[:q] %>"
<ul>
  <% @links.each do |link| %>
    <li>
      Votes: <%= link.votes.where(:up => true).count - link.votes.where(:up => false).count %>

      <% if current_user && current_user.votes.where(:link_id => link.id, :up => true).present? %>
      *
      <% else %>
        <%= link_to "+", votes_path(:vote => {:link_id => link.id, :up => true}), :method => :post %>
      <% end %>


      <% if current_user && current_user.votes.where(:link_id => link.id, :up => false).present? %>
        *
      <% else %>
          <%= link_to "-", votes_path(:vote => {:link_id => link.id, :up => false}), :method => :post %>
      <% end %>

      <%= link_to link.title, link.url %>
      <%= link_to "comments", link %>
    </li>
  <% end %>
</ul>

<%= will_paginate @links %>